# CMake project for Linux, macOS, and Windows located under the `compiler` directory.
name: Compiler

on:
  push:
    branches:
      - master
    tags:
      - "*"

  pull_request:
    branches:
      - master
    paths:
      - "compiler/**"
      - "design/**"
      - "utils/**"

  schedule:
    - cron: "0 0 * * 0,3,5,6" # At 00:00 on Sunday, Wednesday, Friday, and Saturday

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build_compiler:
    if: "!startsWith(github.event.pull_request.title, 'WIP')"
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.container }}
      # Use below line only for hosted runner
      # options: --user root -v "/etc/apt/sources.list:/etc/apt/sources.list:ro" -v "/etc/apt/sources.list.d:/etc/apt/sources.list.d:ro"
      options: --user root
    strategy:
      matrix:
        include:
          # Linux with GCC
          # - os: deb # for self-hosted
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            container: mcr.microsoft.com/devcontainers/cpp:debian-12
            toolchain: null
            nproc: 4
            # nproc: 22 # 22 for self-hosted
            ccache: ccache
          # Linux with Clang
          - os: ubuntu-latest
            c_compiler: clang-16
            cpp_compiler: clang++-16
            container: mcr.microsoft.com/devcontainers/cpp:debian-12
            nproc: 4
            ccache: ccache
          # macOS with Clang
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            container: null
            nproc: 3
            ccache: ccache
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            container: null
            nproc: 4
            ccache: sccache

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: actions/checkout@v4

      - name: Prepare (Linux)
        if: matrix.os == 'deb' || matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build flex bison libspdlog-dev libboost-dev libboost-graph-dev libboost-program-options-dev libgtest-dev ${{ matrix.c_compiler }}
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Prepare (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cmake ninja boost spdlog flex bison googletest tree

      - name: Cache vcpkg
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v4
        with:
          path: |
            vcpkg
            vcpkg_installed
            vcpkg_downloads
          key: vcpkg-${{ matrix.os }}-${{ hashFiles('compiler/vcpkg*') }}

      - name: Cache winflexbison
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v4
        with:
          path: compiler/build/tools/winflexbison/src/win_flex_bison-2.5.25.zip
          key: winflexbison-${{ matrix.os }}-${{ hashFiles('compiler/build/tools/winflexbison/src/win_flex_bison-2.5.25.zip') }}

      - name: Prepare (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          if (Test-Path vcpkg) {
            echo "Using cached vcpkg"
          } else {
            git clone --depth=1 --branch 2024.08.23 https://github.com/microsoft/vcpkg.git
            .\vcpkg\bootstrap-vcpkg.bat
          }
          echo "VCPKG_ROOT=${{ github.workspace }}\\vcpkg" >> $env:GITHUB_ENV
          echo "VCPKG_DEFAULT_TRIPLET=x64-windows" >> $env:GITHUB_ENV
          echo "TOOLCHAIN=${{ github.workspace }}\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake" >> $env:GITHUB_ENV

      - name: Set up ccache/sccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: ${{ matrix.ccache }}
          key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.cpp_compiler }}

      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'

      - name: Configure CMake
        run: |
          cmake -B compiler/build -S compiler -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{ env.TOOLCHAIN }} -DCMAKE_C_COMPILER_LAUNCHER=${{ matrix.ccache }} -DCMAKE_CXX_COMPILER_LAUNCHER=${{ matrix.ccache }} -G Ninja

      - name: Build
        run: cmake --build compiler/build --config ${{env.BUILD_TYPE}} -- -j${{ matrix.nproc }}

      - name: Test
        working-directory: compiler/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
