# CMake project for Linux, macOS, and Windows located under the `compiler` directory.
name: CMake on multiple platforms

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    if: "!startsWith(github.event.pull_request.title, 'WIP')"
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.container }}
      options: --user root
    strategy:
      matrix:
        include:
          # Linux with GCC
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            container: mcr.microsoft.com/devcontainers/cpp:debian-12
          # Linux with Clang
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            container: mcr.microsoft.com/devcontainers/cpp:debian-12
          # macOS with Clang
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            container: null

    steps:
      - uses: actions/checkout@v4

      # Dependency installation on Ubuntu
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build flex bison libspdlog-dev libboost-all-dev libgtest-dev tree

      # Dependency installation on macOS
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cmake ninja boost spdlog flex bison googletest tree

      # CMake configuration step
      - name: Configure CMake
        run: |
          cmake -B compiler/build -S compiler \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -G Ninja
        shell: bash

      # Build step
      - name: Build
        run: cmake --build compiler/build --config ${{env.BUILD_TYPE}} -- -j$(nproc || sysctl -n hw.ncpu || 2)
        shell: bash

      # Test step
      - name: Test
        working-directory: compiler/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
        shell: bash
