# CMake project for Linux, macOS, and Windows located under the `compiler` directory.
name: CMake on multiple platforms

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    if: "!startsWith(github.event.pull_request.title, 'WIP')"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        # compiler: [gcc, clang, msvc]
        compiler: [gcc, clang]
        include:
          # Linux with GCC
          - os: ubuntu-latest
            compiler: gcc
            c_compiler: gcc
            cpp_compiler: g++
          # Linux with Clang
          - os: ubuntu-latest
            compiler: clang
            c_compiler: clang
            cpp_compiler: clang++
          # macOS with Clang
          - os: macos-latest
            compiler: clang
            c_compiler: clang
            cpp_compiler: clang++
          # Windows with MSVC
          # - os: windows-latest
          #   compiler: msvc
          #   cpp_compiler: cl
        exclude:
          # Exclude macOS with GCC
          - os: macos-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang
    steps:
      - uses: actions/checkout@v4

      # Dependency installation on Ubuntu
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build flex bison libspdlog-dev libboost-all-dev libgtest-dev

      - name: Install dependencies and Clang 16 on Ubuntu
        if: matrix.os == 'ubuntu-latest' && matrix.compiler == 'clang'
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg software-properties-common
          # Add the repository for Clang 16
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-16 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-16 100

      # Dependency installation on macOS
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cmake ninja boost spdlog flex bison googletest

      # Dependency installation on Windows (using vcpkg)
      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install boost spdlog flex bison gtest
        shell: powershell

      # CMake configuration step
      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/compiler/build -S ${{github.workspace}}/compiler \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -G Ninja
        shell: bash

      # Build step
      - name: Build
        run: cmake --build ${{github.workspace}}/compiler/build --config ${{env.BUILD_TYPE}} -- -j$(nproc || sysctl -n hw.ncpu || 2)
        shell: bash

      # Test step
      - name: Test
        working-directory: ${{github.workspace}}/compiler/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
        shell: bash
